function [fitresult, gof] = createFit(N, M, sh)
%CREATEFIT(N,M,SH)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : N
%      Y Input : M
%      Z Output: sh
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Aug-2015 20:14:12

% Copyright 2015 The MathWorks, Inc.

%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( N, M, sh );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'sh vs. N, M', 'Location', 'NorthEast' );
% Label axes
xlabel N
ylabel M
zlabel sh
grid on
view( 103.5, 12.0 );


